export { 
    NOTES_FETCH_START,
    NOTES_FETCH_COMPLETE,
    NOTES_FETCH_FAILURE,

    NOTE_ADD_START,
    NOTE_ADD_COMPLETE,
    NOTE_ADD_FAILURE,

    NOTE_GET_START,
    NOTE_GET_COMPLETE,
    NOTE_GET_FAILURE,

    NOTE_EDIT_START,
    NOTE_EDIT_COMPLETE,
    NOTE_EDIT_FAILURE,

    NOTE_DELETE_START,
    NOTE_DELETE_COMPLETE,
    NOTE_DELETE_FAILURE,

    getNoteList,
    addNewNote,
    getNote,
    editNote,
    deleteNote
} from './rootActions';